name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    env:
      USER: ubuntu
      HOST: 3.18.225.147
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

      # Build
      - run: npm run gameCreator_ci
      - run: npm run gameCreator_build

      - run: npm run game_ci
      - run: npm run game_build

      # Deploy
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ env.USER }}@${{ env.HOST }} rm -r game/clients/gameCreator/dist
      - run: ssh -i $HOME/.ssh/key ${{ env.USER }}@${{ env.HOST }} rm -r game/clients/game/dist
      - run: scp -i $HOME/.ssh/key -r clients/gameCreator/dist/ ${{ env.USER }}@${{ env.HOST }}:game/clients/gameCreator
      - run: scp -i $HOME/.ssh/key -r clients/game/dist/ ${{ env.USER }}@${{ env.HOST }}:game/clients/game

      - run: ssh -i $HOME/.ssh/key ${{ env.USER }}@${{ env.HOST }} rm -r game/arts/utils
      - run: scp -i $HOME/.ssh/key -r arts/utils ${{ env.USER }}@${{ env.HOST }}:game/arts

      - run: scp -i $HOME/.ssh/key -r src/ ${{ env.USER }}@${{ env.HOST }}:game/
      - run: scp -i $HOME/.ssh/key index.js ${{ env.USER }}@${{ env.HOST }}:game/
      - run: scp -i $HOME/.ssh/key package.json ${{ env.USER }}@${{ env.HOST }}:game/
